Add ability to run a custom hook during k8s test setup
adobe/rules_gitops pull request #38
Opened 2020-09-23 22:18 UTC by nate-mar

## Description

This change adds the ability to specific a custom hook that will run after the k8s setup is completed but before tests are run. 

## Related Issue

## Motivation and Context

This hook can be used for such things as running pre-test suite setup that is not specific to a single test, or for batching the setup for multiple tests for efficiency.

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-07-21 19:15 UTC, michaelschiff commented on testing/it_sidecar/client/sidecar_client.go
> +func (s *K8STestSetup) testMain(m *testing.M, hook Hook) {
lets make the second param variadic so that users can pass 0 or more hooks to be run

2021-07-21 20:01 UTC, kzadorozhny requested changes

2021-07-21 20:01 UTC, kzadorozhny commented on testing/it_sidecar/client/sidecar_client.go
> +func (s *K8STestSetup) TestMainWithHook(m *testing.M, hook Hook) {
The more robust approach would be to add 2 callbacks. One should fire when the service is ready ( the `FORWARD` command ), and second when all services are ready ( `READY`  command ). This design will allow to handle the situation when one service ready state depends on the test code interactions with another service.

2021-07-21 20:13 UTC, kzadorozhny commented on testing/it_sidecar/client/sidecar_client.go
> +func (s *K8STestSetup) TestMainWithHook(m *testing.M, hook Hook) {
The callback configuration is better to be the part of `K8STestSetup` constructor.

2021-07-23 23:37 UTC, kzadorozhny commented on testing/it_sidecar/client/noop.setup
> +echo "FORWARD foo"
The forward line per [it_sidecar.go#L290](https://github.com/adobe/rules_gitops/blob/eaef1a6189b48bd4cbac6fd77a8cb5a7dcac9586/testing/it_sidecar/it_sidecar.go#L290) is

```go
fmt.Printf("FORWARD %s:%d:%d\n", serviceName, port.Remote, port.Local)
```

2021-07-23 23:42 UTC, kzadorozhny requested changes

2021-07-23 23:42 UTC, kzadorozhny commented on testing/it_sidecar/client/sidecar_client.go
> +	ReadyCallbacks []Callback
I'd make it just one function `ReadyCallback Callback`. it is easy to define `func` you need to notify multiple observers.

2021-07-24 00:29 UTC, kzadorozhny approved these changes

2021-07-24 01:10 UTC, merged